### PR TITLE
Localization - EN to PT

### PR DESCRIPTION
**Pull request by ricardoprins**
- Fixed small grammar issues
- Matched fixes to .js localization files
- Added missing terms

### CODE REVIEW

**Comment by jlooper** [comment]
Wow, thank you so much @ricardoprins !!

**Comment by ricardoprins** [comment]
> Wow, thank you so much @ricardoprins !!

Whenever you need :)

**Comment by jlooper** [comment]
hi @ricadoprins could you also take a look please at the translated strings here:

/app/game/.vuepress/theme/translations

and these:

app/game/.vuepress/theme/utils/items.json

thanks!!

please also add yourself to the credits files!

**Comment by ricardoprins** [comment]
I had checked these files before :) 

I'll add myself then!

**Pull request merged**
